<a href="https://colab.research.google.com/github/MernaAziz/my-projects/blob/main/LSTM_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
#weights :
Wh = np.array([
    [0.1, 0.5, 0.1],
    [0.5, 0.9, 0.3],
    [0.3, 0.2, 0.1]
])

Wx = np.array([
    [0.6, 0.8, 0.4, 0.8],
    [0.2, 0.2, 0.8, 0.7],
    [0.9, 0.8, 0.1, 0.2]
])

Wy = np.array([
    [0.9, 0.8, 0.3],
    [0.2, 0.3, 0.4],
    [0.6, 0.9, 0.1],
    [0.5, 0.0, 0.3]
])



In [3]:
#Input and previous hidden state:

x = np.array([1,0,0,0])
h_prev = np.array([0,0,0])

# compute a1:

a1 = np.dot(Wh, h_prev) + np.dot(Wx, x)

print("a1 = ")
print(a1)


a1 = 
[0.6 0.2 0.9]


In [4]:
#  hidden state :

h1 = np.tanh(a1)

print("\nh1 = ")
print(h1)


h1 = 
[0.53704957 0.19737532 0.71629787]


In [5]:
# output before softmax :

out = np.dot(Wy, h1)


In [6]:
# Softmax:

def softmax(out):
    exp_out = np.exp(out)
    return exp_out / np.sum(exp_out)

y1 = softmax(out)

print("\ny1 = ")
print(y1)


y1 = 
[0.321599   0.2149301  0.24193486 0.22153605]
