<a href="https://colab.research.google.com/github/MernaAziz/my-projects/blob/main/transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# -----------------------------
# 1. Input embeddings
# -----------------------------
X = np.array([
    [1, 0, 1, 0],   # I
    [0, 1, 0, 1],   # love
    [1, 1, 0, 0]    # Tennis
])

d_model = 4
num_heads = 2
d_k = d_model // num_heads

# -----------------------------
# 2. Define weights
# -----------------------------
# Head 1
WQ1 = np.array([
    [1, 0],
    [0, 1],
    [1, 0],
    [0, 1]
])

WK1 = WQ1.copy()
WV1 = WQ1.copy()

# Head 2
WQ2 = np.array([
    [0, 1],
    [1, 0],
    [0, 1],
    [1, 0]
])

WK2 = WQ2.copy()
WV2 = WQ2.copy()

# -----------------------------
# 3. Softmax function
# -----------------------------
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

# -----------------------------
# 4. Attention function
# -----------------------------
def attention(Q, K, V):
    scores = np.matmul(Q, K.T) / np.sqrt(d_k)
    attn_weights = softmax(scores)
    output = np.matmul(attn_weights, V)
    return output

# -----------------------------
# 5. Head 1
# -----------------------------
Q1 = np.matmul(X, WQ1)
K1 = np.matmul(X, WK1)
V1 = np.matmul(X, WV1)

head1 = attention(Q1, K1, V1)

# -----------------------------
# 6. Head 2
# -----------------------------
Q2 = np.matmul(X, WQ2)
K2 = np.matmul(X, WK2)
V2 = np.matmul(X, WV2)

head2 = attention(Q2, K2, V2)

# -----------------------------
# 7. Concatenate heads
# -----------------------------
multi_head = np.concatenate([head1, head2], axis=1)




In [2]:
print("Head 1 Output:\n", head1)
print("\nHead 2 Output:\n", head2)
print("\nMulti-Head Output:\n", multi_head)

Head 1 Output:
 [[1.72252957 0.27747043]
 [0.27747043 1.72252957]
 [1.         1.        ]]

Head 2 Output:
 [[0.27747043 1.72252957]
 [1.72252957 0.27747043]
 [1.         1.        ]]

Multi-Head Output:
 [[1.72252957 0.27747043 0.27747043 1.72252957]
 [0.27747043 1.72252957 1.72252957 0.27747043]
 [1.         1.         1.         1.        ]]
